language: java
sudo: required
dist: trusty
group: edge

matrix:
  fast_finish: true

  include:
    # JDK 10
    - env: JDK_RELEASE='JDK 10'
      install: . ./buildtools/src/install/install-jdk-11.sh

script:
- ./gradlew build

after_success:
  - ./gradlew jacocoRootReport && bash <(curl -s https://codecov.io/bash) || true

env:
  global:
    - CODECOV_TOKEN=2b0b77ea-7b6f-447d-8cf3-e5c070e74c81