language: java
sudo: required
dist: trusty
group: edge

matrix:
  fast_finish: true

  include:
    # JDK 10
    - env: JDK_RELEASE='JDK 10'
      install: . ./buildtools/src/install/install-jdk-10.sh

script:
- ./gradlew build

after_success:
  - ./gradlew jacocoRootReport && bash <(curl -s https://codecov.io/bash) || true

env:
  global:
    - CODECOV_TOKEN=f0022046-6667-4cc4-8fbf-c2524734bbd6